apiVersion: v1
kind: Service
metadata:
  name: todoapp-service-clusterip
  labels:
    app: todolist
spec:
  type: ClusterIP
  selector:
    app: todolist
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
