apiVersion: v1
kind: Service
metadata:
  name: todoapp-service-nodeport
  labels:
    app: todolist
spec:
  type: NodePort
  selector:
    app: todolist
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
