apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod-2
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    ports:
    - containerPort: 8080
    env:
    - name: DEBUG
      value: "False"
    - name: SECRET_KEY
      value: "django-insecure-change-me-in-production"
    - name: ALLOWED_HOSTS
      value: "localhost,127.0.0.1,*"
    - name: DATABASE_ENGINE
      value: "django.db.backends.sqlite3"
    - name: DATABASE_NAME
      value: "/tmp/db.sqlite3"
    livenessProbe:
      httpGet:
        path: /api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5